export const ENDPOINTS = {
  HEALTH: '/api/v1/health',
  IPOS: '/api/v1/ipos',
  IPO_BY_SYMBOL: (symbol: string) => `/api/v1/ipos/${symbol}`,
  CALENDAR: '/api/v1/calendar',
  OPEN: '/api/v1/open',
  UPCOMING: '/api/v1/upcoming',
  CLOSED: '/api/v1/closed',
  ALLOTMENTS: '/api/v1/allotments',
  ALLOTMENT_JOBS: '/api/v1/allotment/jobs',
  ALLOTMENT_JOB_BY_ID: (id: string) => `/api/v1/allotment/jobs/${id}`,
  ALLOTMENT_JOB_RETRY: (id: string) => `/api/v1/allotment/jobs/${id}/retry`,
  PAN_SYNC: '/api/v1/user/pans/sync',
  GMP: '/api/v1/gmp',
  SEARCH: '/api/v1/search',
  STATISTICS: '/api/v1/statistics',
  VERSION: '/api/v1/version',
  ANALYTICS_MARKET: '/api/v1/analytics/market',
  ANALYTICS_PERFORMANCE: '/api/v1/analytics/performance',
  ANALYTICS_SUBSCRIPTION: '/api/v1/analytics/subscription',
  ANALYTICS_ALLOTMENT: '/api/v1/analytics/allotment',
  ANALYTICS_QUALITY: '/api/v1/analytics/quality',
  ANALYTICS_SUMMARY: '/api/v1/analytics/summary',
  ANALYTICS_METRICS: '/api/v1/analytics/metrics',
  ANALYTICS_CONTRACTS: '/api/v1/analytics/contracts',
} as const;

